import { Medicine, User, Order } from './types';

// Mock medicines data - 50+ premium medicines
export const mockMedicines: Medicine[] = [
  {
    id: '1',
    name: 'Aspirin 500mg',
    category: 'Pain Relief',
    price: 149,
    stock: 150,
    description: 'Effective pain reliever and fever reducer',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '2',
    name: 'Amoxicillin 250mg',
    category: 'Antibiotics',
    price: 299,
    stock: 80,
    description: 'Broad-spectrum antibiotic for infections',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '3',
    name: 'Vitamin D3 1000IU',
    category: 'Vitamins',
    price: 199,
    stock: 200,
    description: 'Essential vitamin for bone health',
    manufacturer: 'HealthPlus',
    requiresPrescription: false,
    rating: 4.9,
    image: '💊',
  },
  {
    id: '4',
    name: 'Metformin 500mg',
    category: 'Diabetes Care',
    price: 249,
    stock: 120,
    description: 'Diabetes management medication',
    manufacturer: 'CarePlus',
    requiresPrescription: true,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '5',
    name: 'Ibuprofen 400mg',
    category: 'Pain Relief',
    price: 179,
    stock: 180,
    description: 'Anti-inflammatory pain reliever',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '6',
    name: 'Cetirizine 10mg',
    category: 'Allergy Relief',
    price: 189,
    stock: 90,
    description: 'Non-drowsy allergy relief',
    manufacturer: 'AllergyWorks',
    requiresPrescription: false,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '7',
    name: 'Omeprazole 20mg',
    category: 'Digestive Health',
    price: 269,
    stock: 60,
    description: 'Acid reflux and heartburn relief',
    manufacturer: 'DigestCare',
    requiresPrescription: true,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '8',
    name: 'Lisinopril 5mg',
    category: 'Blood Pressure',
    price: 329,
    stock: 100,
    description: 'Blood pressure management',
    manufacturer: 'HeartCare',
    requiresPrescription: true,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '9',
    name: 'Paracetamol 500mg',
    category: 'Pain Relief',
    price: 129,
    stock: 200,
    description: 'Mild to moderate pain reliever',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.9,
    image: '💊',
  },
  {
    id: '10',
    name: 'Azithromycin 250mg',
    category: 'Antibiotics',
    price: 349,
    stock: 75,
    description: 'Macrolide antibiotic for bacterial infections',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '11',
    name: 'Vitamin B Complex',
    category: 'Vitamins',
    price: 219,
    stock: 180,
    description: 'Complete B vitamin complex supplement',
    manufacturer: 'NutraHealth',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '12',
    name: 'Insulin Glargine',
    category: 'Diabetes Care',
    price: 899,
    stock: 45,
    description: 'Long-acting insulin injection',
    manufacturer: 'DiabetesCare Plus',
    requiresPrescription: true,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '13',
    name: 'Naproxen 250mg',
    category: 'Pain Relief',
    price: 199,
    stock: 110,
    description: 'Long-lasting pain and inflammation relief',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '14',
    name: 'Loratadine 10mg',
    category: 'Allergy Relief',
    price: 169,
    stock: 140,
    description: 'Long-acting antihistamine for allergies',
    manufacturer: 'AllergyWorks',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '15',
    name: 'Ranitidine 150mg',
    category: 'Digestive Health',
    price: 149,
    stock: 85,
    description: 'Reduces stomach acid production',
    manufacturer: 'DigestCare',
    requiresPrescription: true,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '16',
    name: 'Amlodipine 5mg',
    category: 'Blood Pressure',
    price: 289,
    stock: 95,
    description: 'Calcium channel blocker for hypertension',
    manufacturer: 'HeartCare',
    requiresPrescription: true,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '17',
    name: 'Acetaminophen 650mg',
    category: 'Pain Relief',
    price: 159,
    stock: 160,
    description: 'Extra strength pain reliever',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '18',
    name: 'Ciprofloxacin 500mg',
    category: 'Antibiotics',
    price: 319,
    stock: 65,
    description: 'Fluoroquinolone antibiotic',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '19',
    name: 'Calcium Carbonate 500mg',
    category: 'Vitamins',
    price: 139,
    stock: 220,
    description: 'Calcium supplement for bone health',
    manufacturer: 'HealthPlus',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '20',
    name: 'Glibenclamide 5mg',
    category: 'Diabetes Care',
    price: 189,
    stock: 130,
    description: 'Sulfonylurea for diabetes management',
    manufacturer: 'CarePlus',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '21',
    name: 'Ketoprofen 50mg',
    category: 'Pain Relief',
    price: 169,
    stock: 95,
    description: 'NSAID for pain and inflammation',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '22',
    name: 'Doxycycline 100mg',
    category: 'Antibiotics',
    price: 279,
    stock: 70,
    description: 'Tetracycline antibiotic broad spectrum',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '23',
    name: 'Magnesium Glycinate 400mg',
    category: 'Vitamins',
    price: 249,
    stock: 150,
    description: 'Highly absorbable magnesium supplement',
    manufacturer: 'NutraHealth',
    requiresPrescription: false,
    rating: 4.9,
    image: '💊',
  },
  {
    id: '24',
    name: 'Pioglitazone 15mg',
    category: 'Diabetes Care',
    price: 399,
    stock: 55,
    description: 'Thiazolidinedione for diabetes',
    manufacturer: 'CarePlus',
    requiresPrescription: true,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '25',
    name: 'Meloxicam 7.5mg',
    category: 'Pain Relief',
    price: 209,
    stock: 105,
    description: 'Long-acting NSAID for arthritis pain',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '26',
    name: 'Levofloxacin 500mg',
    category: 'Antibiotics',
    price: 359,
    stock: 50,
    description: 'Fluoroquinolone for respiratory infections',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '27',
    name: 'Zinc Supplement 30mg',
    category: 'Vitamins',
    price: 129,
    stock: 190,
    description: 'Immune system support supplement',
    manufacturer: 'HealthPlus',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '28',
    name: 'Voglibose 0.3mg',
    category: 'Diabetes Care',
    price: 219,
    stock: 110,
    description: 'Alpha glucosidase inhibitor for diabetes',
    manufacturer: 'DiabetesCare Plus',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '29',
    name: 'Diclofenac 50mg',
    category: 'Pain Relief',
    price: 139,
    stock: 140,
    description: 'NSAID for acute pain relief',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '30',
    name: 'Trimethoprim-Sulfamethoxazole 400-80mg',
    category: 'Antibiotics',
    price: 189,
    stock: 85,
    description: 'Combination antibiotic for infections',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '31',
    name: 'Iron Supplement 65mg',
    category: 'Vitamins',
    price: 159,
    stock: 170,
    description: 'Iron supplement for anemia',
    manufacturer: 'NutraHealth',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '32',
    name: 'Sitagliptin 50mg',
    category: 'Diabetes Care',
    price: 459,
    stock: 60,
    description: 'DPP-4 inhibitor for type 2 diabetes',
    manufacturer: 'CarePlus',
    requiresPrescription: true,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '33',
    name: 'Indomethacin 25mg',
    category: 'Pain Relief',
    price: 149,
    stock: 120,
    description: 'Potent NSAID for severe pain',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '34',
    name: 'Cephalexin 500mg',
    category: 'Antibiotics',
    price: 249,
    stock: 95,
    description: 'First-generation cephalosporin',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '35',
    name: 'Selenium 200mcg',
    category: 'Vitamins',
    price: 119,
    stock: 200,
    description: 'Antioxidant mineral supplement',
    manufacturer: 'HealthPlus',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '36',
    name: 'Rosiglitazone 4mg',
    category: 'Diabetes Care',
    price: 399,
    stock: 50,
    description: 'Thiazolidinedione diabetes medication',
    manufacturer: 'DiabetesCare Plus',
    requiresPrescription: true,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '37',
    name: 'Piroxicam 20mg',
    category: 'Pain Relief',
    price: 189,
    stock: 100,
    description: 'Long-acting NSAID for inflammation',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '38',
    name: 'Erythromycin 250mg',
    category: 'Antibiotics',
    price: 199,
    stock: 75,
    description: 'Macrolide antibiotic for infections',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '39',
    name: 'Folic Acid 1mg',
    category: 'Vitamins',
    price: 99,
    stock: 250,
    description: 'Essential B vitamin for cell division',
    manufacturer: 'HealthPlus',
    requiresPrescription: false,
    rating: 4.9,
    image: '💊',
  },
  {
    id: '40',
    name: 'Tolbutamide 500mg',
    category: 'Diabetes Care',
    price: 159,
    stock: 140,
    description: 'First-generation sulfonylurea',
    manufacturer: 'CarePlus',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '41',
    name: 'Tenoxicam 20mg',
    category: 'Pain Relief',
    price: 219,
    stock: 85,
    description: 'Oxicam NSAID for pain management',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '42',
    name: 'Norfloxacin 400mg',
    category: 'Antibiotics',
    price: 289,
    stock: 65,
    description: 'Fluoroquinolone for UTI treatment',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '43',
    name: 'Biotin 5mg',
    category: 'Vitamins',
    price: 149,
    stock: 180,
    description: 'B vitamin for hair and nail health',
    manufacturer: 'NutraHealth',
    requiresPrescription: false,
    rating: 4.8,
    image: '💊',
  },
  {
    id: '44',
    name: 'Acarbose 50mg',
    category: 'Diabetes Care',
    price: 229,
    stock: 100,
    description: 'Alpha glucosidase inhibitor',
    manufacturer: 'CarePlus',
    requiresPrescription: true,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '45',
    name: 'Oxaprozin 600mg',
    category: 'Pain Relief',
    price: 249,
    stock: 70,
    description: 'Propionic acid NSAID',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '46',
    name: 'Gatifloxacin 400mg',
    category: 'Antibiotics',
    price: 319,
    stock: 55,
    description: 'Fluoroquinolone for serious infections',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '47',
    name: 'Potassium Gluconate 500mg',
    category: 'Vitamins',
    price: 179,
    stock: 130,
    description: 'Electrolyte supplement for heart health',
    manufacturer: 'HealthPlus',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '48',
    name: 'Miglitol 25mg',
    category: 'Diabetes Care',
    price: 199,
    stock: 95,
    description: 'Alpha glucosidase inhibitor',
    manufacturer: 'DiabetesCare Plus',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
  {
    id: '49',
    name: 'Phenylbutazone 100mg',
    category: 'Pain Relief',
    price: 179,
    stock: 60,
    description: 'NSAID for severe rheumatic conditions',
    manufacturer: 'PharmaCare',
    requiresPrescription: false,
    rating: 4.5,
    image: '💊',
  },
  {
    id: '50',
    name: 'Moxifloxacin 400mg',
    category: 'Antibiotics',
    price: 379,
    stock: 45,
    description: 'Fourth-generation fluoroquinolone',
    manufacturer: 'MediPharm',
    requiresPrescription: true,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '51',
    name: 'Chromium Picolinate 200mcg',
    category: 'Vitamins',
    price: 139,
    stock: 160,
    description: 'Mineral supplement for metabolism',
    manufacturer: 'NutraHealth',
    requiresPrescription: false,
    rating: 4.7,
    image: '💊',
  },
  {
    id: '52',
    name: 'Nateglinide 120mg',
    category: 'Diabetes Care',
    price: 269,
    stock: 80,
    description: 'Meglitinide for postprandial glucose',
    manufacturer: 'CarePlus',
    requiresPrescription: true,
    rating: 4.6,
    image: '💊',
  },
];

// Mock users data
export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'John Customer',
    email: 'customer@example.com',
    password: 'password123', // In real app, this would be hashed
    role: 'customer',
    phone: '+1234567890',
    address: '123 Main St, City, State 12345',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'doctor1',
    name: 'Dr. Sarah Smith',
    email: 'doctor@example.com',
    password: 'password123',
    role: 'doctor',
    phone: '+1987654321',
    licenseNumber: 'DOC123456',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'pharmacist1',
    name: 'Mike Pharmacist',
    email: 'pharmacist@example.com',
    password: 'password123',
    role: 'pharmacist',
    phone: '+1555666777',
    licenseNumber: 'PHARM789012',
    createdAt: new Date('2024-01-12'),
  },
];

// Mock orders data
export const mockOrders: Order[] = [
  {
    id: 'order1',
    userId: 'user1',
    items: [
      { medicineId: '1', quantity: 2, price: 5.99 },
      { medicineId: '3', quantity: 1, price: 8.49 },
    ],
    totalAmount: 20.47,
    status: 'delivered',
    requiresPrescription: false,
    shippingAddress: '123 Main St, City, State 12345',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'order2',
    userId: 'user1',
    items: [{ medicineId: '2', quantity: 1, price: 12.99 }],
    totalAmount: 12.99,
    status: 'processing',
    requiresPrescription: true,
    shippingAddress: '123 Main St, City, State 12345',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-12'),
  },
];

// Helper function to get categories
export const getMedicineCategories = (): string[] => {
  return Array.from(new Set(mockMedicines.map(m => m.category)));
};

// Helper function to search medicines
export const searchMedicines = (query: string): Medicine[] => {
  const lowerQuery = query.toLowerCase();
  return mockMedicines.filter(
    m =>
      m.name.toLowerCase().includes(lowerQuery) ||
      m.category.toLowerCase().includes(lowerQuery) ||
      m.manufacturer.toLowerCase().includes(lowerQuery)
  );
};

// Helper function to filter medicines by category
export const getMedicinesByCategory = (category: string): Medicine[] => {
  return mockMedicines.filter(m => m.category === category);
};
